# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  borealis_config = debug
  borealis_test_config = debug

else ifeq ($(config),release)
  borealis_config = release
  borealis_test_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := borealis borealis-test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

borealis:
ifneq (,$(borealis_config))
	@echo "==== Building borealis ($(borealis_config)) ===="
	@${MAKE} --no-print-directory -C . -f borealis.make config=$(borealis_config)
endif

borealis-test: borealis
ifneq (,$(borealis_test_config))
	@echo "==== Building borealis-test ($(borealis_test_config)) ===="
	@${MAKE} --no-print-directory -C . -f borealis-test.make config=$(borealis_test_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f borealis.make clean
	@${MAKE} --no-print-directory -C . -f borealis-test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   borealis"
	@echo "   borealis-test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"